name: feature_post
description: 动态功能包
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  network:
    path: ../network
  shared:
    path: ../shared
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  extended_tabs: ^4.2.0
  fixnum: ^1.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  device_info_plus: ^11.1.1
