name: feature_chat
description: 聊天功能包
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  network:
    path: ../network
  shared:
    path: ../shared
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  tencent_cloud_chat_sdk: 8.4.6667
